.TH SSTDIO 3 "Version 1.0" "01/02/2024"
.SH NAME
s_stdio \- routines assembly pour l'affichage de chaînes de caractères

.SH SYNOPSIS
.B #include <stdio.h>
.LP
.B void s_puts(const char *str);

.SH DESCRIPTION

La bibliothèque \s_stdio\fP fournit des routines assembly pour l'affichage de chaînes de caractères.

The function \s_puts\fP affiche la chaîne de caractères spécifiée jusqu'à la rencontre d'un caractère nul.

.SH PARAMETERS
.LP
.I str
Pointeur vers la chaîne de caractères à afficher.

.SH RETURN VALUES
La fonction ne renvoie pas de valeur.

.SH SEE ALSO
Other related functions or manual pages.
